name: maglogic
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Core Python
  - python>=3.8,<3.13
  - pip

  # Scientific computing core
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - sympy>=1.8.0

  # Jupyter ecosystem
  - jupyter
  - jupyterlab>=3.0.0
  - notebook>=6.4.0
  - ipywidgets>=7.6.0

  # Visualization
  - plotly>=5.0.0
  - seaborn>=0.11.0
  - bokeh>=2.3.0

  # File I/O and data formats
  - h5py>=3.2.0
  - pillow>=8.3.0
  - imageio>=2.9.0
  - netcdf4>=1.5.0

  # Performance computing
  - numba>=0.54.0
  - dask>=2021.6.0

  # Development tools
  - pytest>=6.2.0
  - pytest-cov>=2.12.0
  - black>=21.0.0
  - flake8>=3.9.0
  - mypy>=0.910

  # System utilities
  - tqdm>=4.61.0
  - pyyaml>=5.4.0
  - click>=8.0.0
  - psutil>=5.8.0

  # Machine learning (conda versions)
  - scikit-learn>=1.0.0
  - pytorch>=1.9.0
  - tensorflow>=2.6.0

  # GUI frameworks
  - pyqt>=5.15.0

  # Documentation
  - sphinx>=4.0.0
  - sphinx_rtd_theme>=0.5.0

  # Additional scientific packages
  - vtk>=9.0.0
  - networkx>=2.6.0
  - astropy>=4.3.0

  # Development and testing
  - pre-commit>=2.13.0
  - memory_profiler>=0.60.0

  # Pip-only packages
  - pip:
    - mayavi>=4.7.0
    - pyvista>=0.32.0
    - meshio>=5.0.0
    - scikit-image>=0.18.0
    - lmfit>=1.0.0
    - myst-parser>=0.15.0
    - sphinx-autodoc-typehints>=1.12.0
    - nbsphinx>=0.8.0
    - bandit>=1.7.0
    - safety>=1.10.0
    - pyqtgraph>=0.12.0
    - colorama>=0.4.0
    - requests>=2.25.0
    - flask>=2.0.0
    - fastapi>=0.70.0
    - -e .  # Install package in development mode